find wav/set1 -name "*.wav" | grep "method1" > wav/set1/method1.list
find wav/set1 -name "*.wav" | grep "method2" > wav/set1/method2.list
find wav/set1 -name "*.wav" | grep "method3" > wav/set1/method3.list
find wav/set2 -name "*.wav" | grep "method1" > wav/set2/method1.list
find wav/set2 -name "*.wav" | grep "method2" > wav/set2/method2.list
find wav/set2 -name "*.wav" | grep "method3" > wav/set2/method3.list
find wav/set3 -name "*.wav" | grep "method1" > wav/set3/method1.list
find wav/set3 -name "*.wav" | grep "method2" > wav/set3/method2.list
find wav/set3 -name "*.wav" | grep "method3" > wav/set3/method3.list
find wav/set4 -name "*.wav" | grep "method1" > wav/set4/method1.list
find wav/set4 -name "*.wav" | grep "method2" > wav/set4/method2.list
find wav/set4 -name "*.wav" | grep "method3" > wav/set4/method3.list
find wav/set5 -name "*.wav" | grep "method1" > wav/set5/method1.list
find wav/set5 -name "*.wav" | grep "method2" > wav/set5/method2.list
find wav/set5 -name "*.wav" | grep "method3" > wav/set5/method3.list
find wav/set6 -name "*.wav" | grep "method1" > wav/set6/method1.list
find wav/set6 -name "*.wav" | grep "method2" > wav/set6/method2.list
find wav/set6 -name "*.wav" | grep "method3" > wav/set6/method3.list
find wav/set7 -name "*.wav" | grep "method1" > wav/set7/method1.list
find wav/set7 -name "*.wav" | grep "method2" > wav/set7/method2.list
find wav/set7 -name "*.wav" | grep "method3" > wav/set7/method3.list
find wav/set8 -name "*.wav" | grep "method1" > wav/set8/method1.list
find wav/set8 -name "*.wav" | grep "method2" > wav/set8/method2.list
find wav/set8 -name "*.wav" | grep "method3" > wav/set8/method3.list
find wav/set9 -name "*.wav" | grep "method1" > wav/set9/method1.list
find wav/set9 -name "*.wav" | grep "method2" > wav/set9/method2.list
find wav/set9 -name "*.wav" | grep "method3" > wav/set9/method3.list
find wav/set10 -name "*.wav" | grep "method1" > wav/set10/method1.list
find wav/set10 -name "*.wav" | grep "method2" > wav/set10/method2.list
find wav/set10 -name "*.wav" | grep "method3" > wav/set10/method3.list


